<?php
// --- DB CONNECTION ---
$host = "localhost:3307";
$user = "root";
$pass = "";
$db   = "tm";  // change to your database name
$conn = new mysqli($host, $user, $pass, $db);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Session start for user authentication
session_start();

// Check if user is logged in (simple implementation)
if (!isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit();
}

// Function to get user profile
function getUserProfile($pdo_ttm, $user_id) {
    try {
        $query = "SELECT user_id, username, full_name, email, role FROM users WHERE user_id = :user_id";
        $stmt = $pdo_ttm->prepare($query);
        $stmt->bindParam(':user_id', $user_id, PDO::PARAM_INT);
        $stmt->execute();
        return $stmt->fetch();
    } catch (PDOException $e) {
        return ['full_name' => 'User', 'role' => 'User'];
    }
}

// Get database connection for user info
try {
    $pdo_ttm = new PDO("mysql:host=localhost:3307;dbname=ttm", "root", "");
    $pdo_ttm->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (PDOException $e) {
    // Fallback if TTM database is not available
    $pdo_ttm = null;
}

// Get user info
$user_profile = ['full_name' => 'User', 'role' => 'User'];
if ($pdo_ttm && isset($_SESSION['user_id'])) {
    $user_profile = getUserProfile($pdo_ttm, $_SESSION['user_id']);
}

// Check if user has appropriate permissions
if ($user_profile['role'] !== 'Admin' && $user_profile['role'] !== 'Supervisor') {
    $is_user = true;
} else {
    $is_user = false;
}

// --- EXPORT FUNCTIONALITY ---
if (isset($_GET['export'])) {
    $format = $_GET['format'] ?? 'csv';
    $filename = "daily_monitoring_" . date('Y-m-d') . "." . ($format === 'excel' ? 'xls' : 'csv');
    
    // Fetch all records
    $result = $conn->query("SELECT * FROM monitoring_reports ORDER BY created_at DESC");
    
    if ($format === 'excel') {
        // Excel format
        header("Content-Type: application/vnd.ms-excel");
        header("Content-Disposition: attachment; filename=\"$filename\"");
        
        $sep = "\t"; // tab character
        
        // Column headers
        echo "ID" . $sep;
        echo "Report Type" . $sep;
        echo "Start Date" . $sep;
        echo "End Date" . $sep;
        echo "Low Traffic" . $sep;
        echo "Medium Traffic" . $sep;
        echo "High Traffic" . $sep;
        echo "Generated By" . $sep;
        echo "Created At" . "\n";
        
        // Data rows
        while($row = $result->fetch_assoc()) {
            echo $row['id'] . $sep;
            echo $row['report_type'] . $sep;
            echo $row['start_date'] . $sep;
            echo $row['end_date'] . $sep;
            echo $row['total_low'] . $sep;
            echo $row['total_medium'] . $sep;
            echo $row['total_high'] . $sep;
            echo $row['generated_by'] . $sep;
            echo $row['created_at'] . "\n";
        }
    } else {
        // CSV format (default)
        header("Content-Type: text/csv");
        header("Content-Disposition: attachment; filename=\"$filename\"");
        
        $output = fopen('php://output', 'w');
        
        // Column headers
        fputcsv($output, array('ID', 'Report Type', 'Start Date', 'End Date', 'Low Traffic', 'Medium Traffic', 'High Traffic', 'Generated By', 'Created At'));
        
        // Data rows
        while($row = $result->fetch_assoc()) {
            fputcsv($output, $row);
        }
        
        fclose($output);
    }
    exit();
}

// --- GENERATE REPORT ---
if (isset($_POST['generate_report'])) {
    $report_type = $_POST['report_type'];
    $start_date = $_POST['start_date'];
    $end_date = $_POST['end_date'];

    // Validate dates
    if ($start_date > $end_date) {
        $_SESSION['alert'] = [
            'type' => 'error',
            'title' => 'Error!',
            'message' => 'Start date cannot be after end date.'
        ];
    } else {
        // Get traffic data
        $sql = "SELECT volume, COUNT(*) as total 
                FROM traffic_logs 
                WHERE DATE(log_date) BETWEEN '$start_date' AND '$end_date'
                GROUP BY volume";
        $result = $conn->query($sql);
        
        $low = $medium = $high = 0;
        while($row = $result->fetch_assoc()) {
            if ($row['volume'] == 'Low') $low = $row['total'];
            if ($row['volume'] == 'Medium') $medium = $row['total'];
            if ($row['volume'] == 'High') $high = $row['total'];
        }

        $total = $low + $medium + $high;
        
        // Store report data in session for display
        $_SESSION['report_data'] = [
            'report_type' => $report_type,
            'start_date' => $start_date,
            'end_date' => $end_date,
            'low' => $low,
            'medium' => $medium,
            'high' => $high,
            'total' => $total
        ];
        
        $_SESSION['alert'] = [
            'type' => 'success',
            'title' => 'Success!',
            'message' => 'Report generated successfully.'
        ];
    }
    header("Location: " . $_SERVER['PHP_SELF']);
    exit();
}

// --- SAVE REPORT (Only for admin/supervisor) ---
if (isset($_POST['save_report']) && !$is_user) {
    $report_type = $_POST['report_type'];
    $start_date = $_POST['start_date'];
    $end_date = $_POST['end_date'];
    $low = $_POST['low'];
    $medium = $_POST['medium'];
    $high = $_POST['high'];
    
    $admin_id = $_SESSION['user_id'];

    $sql = "INSERT INTO monitoring_reports 
            (report_type, start_date, end_date, total_low, total_medium, total_high, generated_by) 
            VALUES ('$report_type', '$start_date', '$end_date', '$low', '$medium', '$high', '$admin_id')";
    
    if ($conn->query($sql)) {
        $_SESSION['alert'] = [
            'type' => 'success',
            'title' => 'Success!',
            'message' => 'Report saved successfully.'
        ];
        
        // Clear the report data from session
        unset($_SESSION['report_data']);
    } else {
        $_SESSION['alert'] = [
            'type' => 'error',
            'title' => 'Error!',
            'message' => 'Failed to save report: ' . $conn->error
        ];
    }
    header("Location: " . $_SERVER['PHP_SELF']);
    exit();
}

// --- DELETE REPORT (Only for admin) ---
if (isset($_GET['delete_report']) && $user_profile['role'] === 'Admin') {
    $report_id = $_GET['delete_report'];
    
    $sql = "DELETE FROM monitoring_reports WHERE id = $report_id";
    
    if ($conn->query($sql)) {
        $_SESSION['alert'] = [
            'type' => 'success',
            'title' => 'Success!',
            'message' => 'Report deleted successfully.'
        ];
    } else {
        $_SESSION['alert'] = [
            'type' => 'error',
            'title' => 'Error!',
            'message' => 'Failed to delete report: ' . $conn->error
        ];
    }
    header("Location: " . $_SERVER['PHP_SELF']);
    exit();
}

// --- READ (Fetch recent reports) ---
$recent_reports = $conn->query("SELECT mr.*, u.username 
                                FROM monitoring_reports mr 
                                LEFT JOIN ttm.users u ON mr.generated_by = u.user_id 
                                ORDER BY mr.created_at DESC 
                                LIMIT 5");

// Get stats data for cards
$today = date('Y-m-d');
$reports_today = $conn->query("SELECT COUNT(*) as count FROM monitoring_reports WHERE DATE(created_at) = '$today'")->fetch_assoc()['count'];
$total_reports = $conn->query("SELECT COUNT(*) as count FROM monitoring_reports")->fetch_assoc()['count'];
$avg_reports = $conn->query("SELECT COUNT(*) / COUNT(DISTINCT DATE(created_at)) as avg FROM monitoring_reports")->fetch_assoc()['avg'];
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Daily Monitoring Reports - User</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <style>
    :root {
      --primary: #0d6efd;
      --primary-dark: #0b5ed7;
      --primary-light: #3d85e4;
      --primary-gradient: linear-gradient(135deg, #0d6efd 0%, #3d85e4 100%);
      --secondary: #6c757d;
      --accent: #fd7e14;
      --success: #198754;
      --warning: #ffc107;
      --danger: #dc3545;
      --dark: #1e293b;
      --light: #f8fafc;
      --gray-100: #f1f5f9;
      --gray-200: #e2e8f0;
      --gray-300: #cbd5e1;
      --gray-800: #334155;
      --sidebar-width: 280px;
      --header-height: 80px;
      --card-radius: 16px;
      --card-shadow: 0 10px 30px rgba(13, 110, 253, 0.1);
      --transition: all 0.3s ease;
    }
    
    * {
      font-family: 'Poppins', sans-serif;
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      background-color: #f9fafb;
      color: #334155;
      font-weight: 400;
      overflow-x: hidden;
      background: linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%);
      min-height: 100vh;
    }
    
    /* Layout */
    .dashboard-container {
      display: flex;
      min-height: 100vh;
    }
    
    /* Sidebar */
    .sidebar {
      width: var(--sidebar-width);
      background: var(--dark);
      color: white;
      height: 100vh;
      position: fixed;
      left: 0;
      top: 0;
      padding: 1.5rem 1rem;
      transition: var(--transition);
      z-index: 1000;
      overflow-y: auto;
      box-shadow: 5px 0 15px rgba(0, 0, 0, 0.1);
    }
    
    .sidebar-header {
      display: flex;
      align-items: center;
      padding: 0 0.5rem 1.5rem;
      border-bottom: 1px solid rgba(255, 255, 255, 0.1);
    }
    
    .sidebar-header img {
      width: 40px;
      height: 40px;
      border-radius: 8px;
      margin-right: 12px;
      object-fit: cover;
    }
    
    .sidebar-header .text {
      font-weight: 600;
      font-size: 16px;
      line-height: 1.3;
      font-family: 'Montserrat', sans-serif;
    }
    
    .sidebar-header .text small {
      font-size: 12px;
      opacity: 0.7;
      font-weight: 400;
    }
    
    .sidebar-menu {
      margin-top: 2rem;
    }
    
    .sidebar-section {
      font-size: 12px;
      text-transform: uppercase;
      letter-spacing: 1px;
      padding: 0.75rem 0.5rem;
      color: #94a3b8;
      font-weight: 600;
    }
    
    .sidebar-link {
      display: flex;
      align-items: center;
      padding: 0.75rem 1rem;
      border-radius: 8px;
      color: #cbd5e1;
      text-decoration: none;
      transition: var(--transition);
      margin-bottom: 0.25rem;
      position: relative;
      overflow: hidden;
    }
    
    .sidebar-link::before {
      content: '';
      position: absolute;
      left: -10px;
      top: 0;
      height: 100%;
      width: 4px;
      background: var(--primary);
      opacity: 0;
      transition: var(--transition);
    }
    
    .sidebar-link:hover, .sidebar-link.active {
      background: rgba(255, 255, 255, 0.08);
      color: white;
      transform: translateX(5px);
    }
    
    .sidebar-link:hover::before, .sidebar-link.active::before {
      opacity: 1;
      left: 0;
    }
    
    .sidebar-link i {
      font-size: 1.25rem;
      margin-right: 12px;
      width: 24px;
      text-align: center;
      transition: var(--transition);
    }
    
    .sidebar-link:hover i, .sidebar-link.active i {
      color: var(--primary);
      transform: scale(1.1);
    }
    
    .sidebar-link .text {
      font-size: 14px;
      font-weight: 500;
      transition: var(--transition);
    }
    
    .sidebar-dropdown {
      padding-left: 2.5rem;
    }
    
    .sidebar-dropdown-link {
      display: block;
      padding: 0.6rem 1rem;
      color: #94a3b8;
      text-decoration: none;
      font-size: 0.9rem;
      transition: var(--transition);
      border-radius: 6px;
      margin-bottom: 0.2rem;
    }
    
    .sidebar-dropdown-link:hover {
      color: white;
      background: rgba(255, 255, 255, 0.05);
    }
    
    .dropdown-toggle {
      cursor: pointer;
    }
    
    /* Main Content */
    .main-content {
      flex: 1;
      margin-left: var(--sidebar-width);
      padding: 2rem;
      transition: var(--transition);
    }
    
    /* Header */
    .dashboard-header {
      background: rgba(255, 255, 255, 0.9);
      backdrop-filter: blur(10px);
      border-radius: var(--card-radius);
      padding: 1.5rem;
      margin-bottom: 2rem;
      box-shadow: var(--card-shadow);
      display: flex;
      align-items: center;
      justify-content: space-between;
      border: 1px solid rgba(13, 110, 253, 0.1);
      position: relative;
      overflow: hidden;
    }
    
    .dashboard-header::before {
      content: '';
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 4px;
      background: var(--primary-gradient);
    }
    
    .page-title h1 {
      font-size: 28px;
      font-weight: 700;
      color: var(--dark);
      margin-bottom: 0.25rem;
      font-family: 'Montserrat', sans-serif;
      background: var(--primary-gradient);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      background-clip: text;
    }
    
    .page-title p {
      color: var(--secondary);
      margin-bottom: 0;
      font-size: 14px;
    }
    
    .header-actions {
      display: flex;
      align-items: center;
      gap: 1rem;
    }
    
    .user-info {
      text-align: right;
    }
    
    .user-info .fw-medium {
      font-weight: 500;
      color: var(--dark);
    }
    
    .user-info .text-muted {
      font-size: 0.85rem;
    }
    
    /* Stats Cards */
    .stats-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
      gap: 1.5rem;
      margin-bottom: 2rem;
    }
    
    .stat-card {
      background: white;
      border-radius: var(--card-radius);
      padding: 1.5rem;
      box-shadow: var(--card-shadow);
      transition: var(--transition);
      border: 1px solid rgba(13, 110, 253, 0.1);
      position: relative;
      overflow: hidden;
    }
    
    .stat-card:hover {
      transform: translateY(-5px);
      box-shadow: 0 15px 35px rgba(13, 110, 253, 0.15);
    }
    
    .stat-card::before {
      content: '';
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 4px;
      background: var(--primary-gradient);
    }
    
    .stat-card-icon {
      width: 60px;
      height: 60px;
      border-radius: 12px;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 24px;
      margin-bottom: 1rem;
      background: rgba(13, 110, 253, 0.1);
      color: var(--primary);
    }
    
    .stat-card-title {
      font-size: 14px;
      color: var(--secondary);
      margin-bottom: 0.5rem;
    }
    
    .stat-card-value {
      font-size: 28px;
      font-weight: 700;
      color: var(--dark);
      margin-bottom: 0.5rem;
      font-family: 'Montserrat', sans-serif;
    }
    
    .stat-card-change {
      font-size: 13px;
      display: flex;
      align-items: center;
      gap: 0.25rem;
    }
    
    .stat-card-change.up {
      color: var(--success);
    }
    
    .stat-card-change.down {
      color: var(--danger);
    }
    
    /* Content Card */
    .content-card {
      background: white;
      border-radius: var(--card-radius);
      padding: 2rem;
      box-shadow: var(--card-shadow);
      margin-bottom: 2rem;
      border: 1px solid rgba(13, 110, 253, 0.1);
    }
    
    .card-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-bottom: 1.5rem;
      flex-wrap: wrap;
      gap: 1rem;
    }
    
    .card-title {
      font-size: 20px;
      font-weight: 600;
      color: var(--dark);
      font-family: 'Montserrat', sans-serif;
    }
    
    .card-actions {
      display: flex;
      gap: 0.75rem;
    }
    
    /* Buttons */
    .btn {
      border-radius: 8px;
      padding: 0.6rem 1.25rem;
      font-weight: 500;
      font-size: 14px;
      transition: var(--transition);
      display: inline-flex;
      align-items: center;
      justify-content: center;
      gap: 0.5rem;
      border: none;
      cursor: pointer;
    }
    
    .btn-primary {
      background: var(--primary);
    }
    
    .btn-primary:hover {
      background: var(--primary-dark);
      transform: translateY(-2px);
      box-shadow: 0 5px 15px rgba(13, 110, 253, 0.3);
    }
    
    .btn-success {
      background: var(--success);
    }
    
    .btn-success:hover {
      background: #157347;
      transform: translateY(-2px);
      box-shadow: 0 5px 15px rgba(25, 135, 84, 0.3);
    }
    
    .btn-danger {
      background: var(--danger);
    }
    
    .btn-danger:hover {
      background: #bb2d3b;
      transform: translateY(-2px);
      box-shadow: 0 5px 15px rgba(220, 53, 69, 0.3);
    }
    
    .btn-outline-primary {
      background: transparent;
      border: 1px solid var(--primary);
      color: var(--primary);
    }
    
    .btn-outline-primary:hover {
      background: var(--primary);
      color: white;
      transform: translateY(-2px);
      box-shadow: 0 5px 15px rgba(13, 110, 253, 0.3);
    }
    
    /* Forms */
    .form-group {
      margin-bottom: 1.5rem;
    }
    
    .form-label {
      font-weight: 500;
      margin-bottom: 0.5rem;
      color: var(--dark);
      font-size: 14px;
    }
    
    .form-control {
      border-radius: 8px;
      padding: 0.75rem 1rem;
      border: 1px solid var(--gray-300);
      transition: var(--transition);
      font-size: 14px;
    }
    
    .form-control:focus {
      border-color: var(--primary);
      box-shadow: 0 0 0 0.25rem rgba(13, 110, 253, 0.25);
    }
    
    /* Tables */
    .table-container {
      border-radius: var(--card-radius);
      overflow: hidden;
      box-shadow: 0 5px 15px rgba(0, 0, 0, 0.05);
      border: 1px solid var(--gray-200);
    }
    
    .table {
      margin-bottom: 0;
    }
    
    .table thead th {
      background: var(--primary-gradient);
      color: white;
      font-weight: 600;
      padding: 1rem;
      border: none;
      font-size: 14px;
    }
    
    .table tbody td {
      padding: 1rem;
      vertical-align: middle;
      border-color: var(--gray-200);
      font-size: 14px;
    }
    
    .table tbody tr:hover {
      background-color: rgba(13, 110, 253, 0.03);
    }
    
    .badge {
      padding: 0.5rem 0.75rem;
      border-radius: 6px;
      font-weight: 500;
      font-size: 12px;
    }
    
    .badge-primary {
      background: rgba(13, 110, 253, 0.1);
      color: var(--primary);
    }
    
    .badge-success {
      background: rgba(25, 135, 84, 0.1);
      color: var(--success);
    }
    
    .badge-warning {
      background: rgba(255, 193, 7, 0.1);
      color: var(--warning);
    }
    
    .badge-danger {
      background: rgba(220, 53, 69, 0.1);
      color: var(--danger);
    }
    
    /* Report Results */
    .report-results {
      background: rgba(13, 110, 253, 0.05);
      border-radius: var(--card-radius);
      padding: 2rem;
      margin-top: 2rem;
      border: 1px dashed var(--primary);
    }
    
    .results-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 1.5rem;
      flex-wrap: wrap;
      gap: 1rem;
    }
    
    .results-title {
      font-size: 18px;
      font-weight: 600;
      color: var(--primary);
      font-family: 'Montserrat', sans-serif;
    }
    
    .traffic-stats {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 1.5rem;
      margin-bottom: 2rem;
    }
    
    .traffic-stat {
      background: white;
      border-radius: 12px;
      padding: 1.5rem;
      text-align: center;
      box-shadow: 0 5px 15px rgba(0, 0, 0, 0.05);
    }
    
    .traffic-stat-value {
      font-size: 32px;
      font-weight: 700;
      margin-bottom: 0.5rem;
      font-family: 'Montserrat', sans-serif;
    }
    
    .traffic-stat-label {
      font-size: 14px;
      color: var(--secondary);
    }
    
    .traffic-stat.low .traffic-stat-value {
      color: var(--success);
    }
    
    .traffic-stat.medium .traffic-stat-value {
      color: var(--warning);
    }
    
    .traffic-stat.high .traffic-stat-value {
      color: var(--danger);
    }
    
    /* Responsive */
    @media (max-width: 992px) {
      .sidebar {
        transform: translateX(-100%);
      }
      
      .sidebar.active {
        transform: translateX(0);
      }
      
      .main-content {
        margin-left: 0;
      }
      
      .sidebar-toggle {
        display: block !important;
      }
    }
    
    @media (max-width: 768px) {
      .stats-grid {
        grid-template-columns: 1fr;
      }
      
      .header-actions {
        flex-direction: column;
        align-items: flex-start;
        gap: 0.5rem;
      }
    }
    
    /* Toggle Button */
    .sidebar-toggle {
      display: none;
      position: fixed;
      bottom: 20px;
      left: 20px;
      z-index: 1100;
      width: 50px;
      height: 50px;
      border-radius: 50%;
      background: var(--primary);
      color: white;
      align-items: center;
      justify-content: center;
      box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);
      cursor: pointer;
    }
    
    /* Footer */
    .dashboard-footer {
      text-align: center;
      padding: 1.5rem;
      color: var(--secondary);
      font-size: 14px;
      margin-top: 2rem;
      border-top: 1px solid var(--gray-200);
    }
    
    /* Custom Utilities */
    .text-primary { color: var(--primary) !important; }
    .text-success { color: var(--success) !important; }
    .text-warning { color: var(--warning) !important; }
    .text-danger { color: var(--danger) !important; }
    .text-dark { color: var(--dark) !important; }
    .text-secondary { color: var(--secondary) !important; }
  </style>
</head>
<body>
  <!-- Sidebar Toggle Button -->
  <div class="sidebar-toggle">
    <i class='bx bx-menu'></i>
  </div>
      <!-- Sidebar -->
        <div class="sidebar">
            <div class="sidebar-header">
                <img src="img/ttm.png" alt="Logo">
                <div class="text">
                    Quezon City<br>
                    <small>Traffic Management System</small>
                </div>
            </div>
            
            <div class="sidebar-menu">
                <div class="sidebar-section">Main Navigation</div>
                <a href="../dashboard/dashboard.php" class="sidebar-link ">
                    <i class='bx bx-home'></i>
                    <span class="text">Dashboard</span>
                </a>

                <!-- Traffic Reporting -->
                <div class="sidebar-section mt-4">Traffic Services</div>
                <a href="TM/manual_logs/user_traffic_log.php" class="sidebar-link ">
                    <i class='bx bx-traffic-cone'></i>
                    <span class="text">Report Traffic</span>
                </a>
                
                <a href="TM/daily_monitoring/user_daily_monitoring.php" class="sidebar-link">
                    <i class='bx bx-road'></i>
                    <span class="text">Daily Monitoring</span>
                </a>
                
                <a href="RTR/post_dashboard/user_road_updates.php" class="sidebar-link active">
                    <i class='bx bx-error-circle'></i>
                    <span class="text">Post Dashboard</span>
                </a>
                  <a href="../../RTR/road_condition_map/road_condition_map.php" class="sidebar-link">
                    <i class='bx bx-error-circle'></i>
                    <span class="text">Road Condition</span>
                </a>
                  <a href="../../AVR/report_management/submit_citizen_report.php" class="sidebar-link">
                    <i class='bx bx-error-circle'></i>
                    <span class="text">Report Management</span>
                </a>
                  <a href="../../AVR/evidence_handling/evidence_user.php" class="sidebar-link">
                    <i class='bx bx-error-circle'></i>
                    <span class="text">Evidence Handling</span>
                </a>
                  <a href="../../VRD/routing_analytics/routing_analytics.php" class="sidebar-link">
                    <i class='bx bx-error-circle'></i>
                    <span class="text">Routing Analysis</span>
                </a>
                  <a href="../../PT/real_time_tracking/real_time_tracking.php" class="sidebar-link">
                    <i class='bx bx-error-circle'></i>
                    <span class="text">Real-Time Tracking</span>
                </a>
                  <a href="../../PTS/permit_application_processing/permit_application_processing.php" class="sidebar-link">
                    <i class='bx bx-error-circle'></i>
                    <span class="text">Permit Application</span>
                </a>
                  <a href="../../PTS/payment_settlement_management/payment_settlement_management.php" class="sidebar-link">
                    <i class='bx bx-error-circle'></i>
                    <span class="text">Payment & Settlement</span>
                </a>
           
                
                <div class="sidebar-section mt-4">User</div>
                <a href="profile.php" class="sidebar-link">
                    <i class='bx bx-user'></i>
                    <span class="text">Profile</span>
                </a>
                <a href="../logout.php" class="sidebar-link">
                    <i class='bx bx-log-out'></i>
                    <span class="text">Logout</span>
                </a>
            </div>
        </div>
  <!-- Main Content -->
  <div class="dashboard-container">
    <div class="main-content">
      <!-- Header -->
      <div class="dashboard-header">
        <div class="page-title">
          <h1>Daily Monitoring Reports</h1>
          <p>User Access - View and generate traffic monitoring reports</p>
        </div>
        <div class="header-actions">
          <div class="user-info">
            <div class="fw-medium"><?= htmlspecialchars($user_profile['full_name']) ?></div>
            <div class="text-muted"><?= htmlspecialchars($user_profile['role']) ?></div>
          </div>
          <a href="../../logout.php" class="btn btn-outline-primary">
            <i class='bx bx-log-out'></i> Logout
          </a>
        </div>
      </div>
      
      <!-- Stats Cards -->
      <div class="stats-grid">
        <div class="stat-card">
          <div class="stat-card-icon">
            <i class='bx bx-file'></i>
          </div>
          <div class="stat-card-title">Reports Today</div>
          <div class="stat-card-value"><?= $reports_today ?></div>
          <div class="stat-card-change up">
            <i class='bx bx-up-arrow-alt'></i> 2.5% from yesterday
          </div>
        </div>
        
        <div class="stat-card">
          <div class="stat-card-icon">
            <i class='bx bx-stats'></i>
          </div>
          <div class="stat-card-title">Total Reports</div>
          <div class="stat-card-value"><?= $total_reports ?></div>
          <div class="stat-card-change up">
            <i class='bx bx-up-arrow-alt'></i> 12% this month
          </div>
        </div>
        
        <div class="stat-card">
          <div class="stat-card-icon">
            <i class='bx bx-calendar'></i>
          </div>
          <div class="stat-card-title">Avg. Daily Reports</div>
          <div class="stat-card-value"><?= round($avg_reports, 1) ?></div>
          <div class="stat-card-change up">
            <i class='bx bx-up-arrow-alt'></i> 5.3% this quarter
          </div>
        </div>
      </div>
      
      <!-- Generate Report Form -->
      <div class="content-card">
        <div class="card-header">
          <h2 class="card-title">Generate New Report</h2>
        </div>
        
        <form method="POST" action="">
          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <label class="form-label">Report Type</label>
                <select class="form-control" name="report_type" required>
                  <option value="">Select Report Type</option>
                  <option value="Daily">Daily Report</option>
                  <option value="Weekly">Weekly Report</option>
                  <option value="Monthly">Monthly Report</option>
                  <option value="Custom">Custom Date Range</option>
                </select>
              </div>
            </div>
            
            <div class="col-md-4">
              <div class="form-group">
                <label class="form-label">Start Date</label>
                <input type="date" class="form-control" name="start_date" required>
              </div>
            </div>
            
            <div class="col-md-4">
              <div class="form-group">
                <label class="form-label">End Date</label>
                <input type="date" class="form-control" name="end_date" required>
              </div>
            </div>
          </div>
          
          <div class="d-flex justify-content-end">
            <button type="submit" name="generate_report" class="btn btn-primary">
              <i class='bx bx-plus'></i> Generate Report
            </button>
          </div>
        </form>
      </div>
      
      <!-- Report Results -->
      <?php if (isset($_SESSION['report_data'])): 
        $report = $_SESSION['report_data'];
      ?>
      <div class="report-results">
        <div class="results-header">
          <h3 class="results-title">Report Generated Successfully</h3>
          <div class="card-actions">
            <?php if (!$is_user): ?>
            <form method="POST" action="" class="d-inline">
              <input type="hidden" name="report_type" value="<?= $report['report_type'] ?>">
              <input type="hidden" name="start_date" value="<?= $report['start_date'] ?>">
              <input type="hidden" name="end_date" value="<?= $report['end_date'] ?>">
              <input type="hidden" name="low" value="<?= $report['low'] ?>">
              <input type="hidden" name="medium" value="<?= $report['medium'] ?>">
              <input type="hidden" name="high" value="<?= $report['high'] ?>">
              <button type="submit" name="save_report" class="btn btn-success">
                <i class='bx bx-save'></i> Save Report
              </button>
            </form>
            <?php endif; ?>
            <a href="?export=csv" class="btn btn-outline-primary">
              <i class='bx bx-download'></i> Export CSV
            </a>
            <a href="?export=excel" class="btn btn-outline-primary">
              <i class='bx bx-download'></i> Export Excel
            </a>
          </div>
        </div>
        
        <div class="row mb-4">
          <div class="col-md-6">
            <div class="card bg-light">
              <div class="card-body">
                <h5 class="card-title">Report Details</h5>
                <table class="table table-borderless">
                  <tr>
                    <td width="40%"><strong>Report Type:</strong></td>
                    <td><?= $report['report_type'] ?></td>
                  </tr>
                  <tr>
                    <td><strong>Date Range:</strong></td>
                    <td><?= $report['start_date'] ?> to <?= $report['end_date'] ?></td>
                  </tr>
                  <tr>
                    <td><strong>Generated On:</strong></td>
                    <td><?= date('Y-m-d H:i:s') ?></td>
                  </tr>
                  <tr>
                    <td><strong>Generated By:</strong></td>
                    <td><?= htmlspecialchars($user_profile['full_name']) ?></td>
                  </tr>
                </table>
              </div>
            </div>
          </div>
          
          <div class="col-md-6">
            <div class="card bg-light">
              <div class="card-body">
                <h5 class="card-title">Summary</h5>
                <table class="table table-borderless">
                  <tr>
                    <td width="40%"><strong>Total Records:</strong></td>
                    <td><?= $report['total'] ?></td>
                  </tr>
                  <tr>
                    <td><strong>Low Traffic:</strong></td>
                    <td><?= $report['low'] ?> (<?= $report['total'] > 0 ? round(($report['low'] / $report['total']) * 100, 2) : 0 ?>%)</td>
                  </tr>
                  <tr>
                    <td><strong>Medium Traffic:</strong></td>
                    <td><?= $report['medium'] ?> (<?= $report['total'] > 0 ? round(($report['medium'] / $report['total']) * 100, 2) : 0 ?>%)</td>
                  </tr>
                  <tr>
                    <td><strong>High Traffic:</strong></td>
                    <td><?= $report['high'] ?> (<?= $report['total'] > 0 ? round(($report['high'] / $report['total']) * 100, 2) : 0 ?>%)</td>
                  </tr>
                </table>
              </div>
            </div>
          </div>
        </div>
        
        <div class="traffic-stats">
          <div class="traffic-stat low">
            <div class="traffic-stat-value"><?= $report['low'] ?></div>
            <div class="traffic-stat-label">Low Traffic Incidents</div>
          </div>
          
          <div class="traffic-stat medium">
            <div class="traffic-stat-value"><?= $report['medium'] ?></div>
            <div class="traffic-stat-label">Medium Traffic Incidents</div>
          </div>
          
          <div class="traffic-stat high">
            <div class="traffic-stat-value"><?= $report['high'] ?></div>
            <div class="traffic-stat-label">High Traffic Incidents</div>
          </div>
        </div>
      </div>
      <?php endif; ?>
      
      <!-- Recent Reports -->
      <div class="content-card">
        <div class="card-header">
          <h2 class="card-title">Recent Reports</h2>
          <div class="card-actions">
            <a href="?export=csv" class="btn btn-outline-primary">
              <i class='bx bx-download'></i> Export All
            </a>
          </div>
        </div>
        
        <div class="table-container">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>ID</th>
                <th>Report Type</th>
                <th>Date Range</th>
                <th>Low Traffic</th>
                <th>Medium Traffic</th>
                <th>High Traffic</th>
                <th>Generated By</th>
                <th>Created At</th>
                <?php if (!$is_user): ?>
                <th>Actions</th>
                <?php endif; ?>
              </tr>
            </thead>
            <tbody>
              <?php while($report = $recent_reports->fetch_assoc()): ?>
              <tr>
                <td><?= $report['id'] ?></td>
                <td><span class="badge badge-primary"><?= $report['report_type'] ?></span></td>
                <td><?= $report['start_date'] ?> to <?= $report['end_date'] ?></td>
                <td><?= $report['total_low'] ?></td>
                <td><?= $report['total_medium'] ?></td>
                <td><?= $report['total_high'] ?></td>
                <td><?= $report['username'] ?? 'Unknown' ?></td>
                <td><?= $report['created_at'] ?></td>
                <?php if (!$is_user): ?>
                <td>
                  <div class="btn-group">
                    <a href="?export=csv&id=<?= $report['id'] ?>" class="btn btn-sm btn-outline-primary">
                      <i class='bx bx-download'></i>
                    </a>
                    <?php if ($user_profile['role'] === 'Admin'): ?>
                    <a href="?delete_report=<?= $report['id'] ?>" class="btn btn-sm btn-outline-danger" onclick="return confirm('Are you sure you want to delete this report?')">
                      <i class='bx bx-trash'></i>
                    </a>
                    <?php endif; ?>
                  </div>
                </td>
                <?php endif; ?>
              </tr>
              <?php endwhile; ?>
            </tbody>
          </table>
        </div>
      </div>
      
      <!-- Footer -->
      <div class="dashboard-footer">
        <p>&copy; 2023 Quezon City Traffic Management System. All rights reserved.</p>
      </div>
    </div>
  </div>
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
  <script>
    // Toggle sidebar on mobile
    document.querySelector('.sidebar-toggle').addEventListener('click', function() {
      document.querySelector('.sidebar').classList.toggle('active');
    });
    
    // Handle alerts from PHP
    <?php if (isset($_SESSION['alert'])): ?>
    Swal.fire({
      icon: '<?= $_SESSION['alert']['type'] ?>',
      title: '<?= $_SESSION['alert']['title'] ?>',
      text: '<?= $_SESSION['alert']['message'] ?>',
      timer: 3000,
      showConfirmButton: false
    });
    <?php unset($_SESSION['alert']); endif; ?>
  </script>
</body>
</html>
<?php $conn->close(); ?>